### ISSUE TITLE
Проверка лабораторной работы 6

### ISSUE THREAD

**Issue by DX37** [DX37/Lab6#1]
Работу выполнил:
* Курносенко Максим Сергеевич

Ссылка на Travis: https://travis-ci.org/DX37/Lab6

To: @evgeny-p

**Comment by evgeny-p** [comment]
> Ссылка на Travis: https://travis-ci.org/DX37/Lab6

Эта ссылка уже есть в README.md

Часть, связанная с CI, принимается.
Замечания по предыдущим работам предлагаю исправлять в этом репозитории.

**Comment by DX37** [comment]
Вроде как всё исправил.

**Comment by evgeny-p** [comment]
1. Серьезный недостаток функции: вычисления смешаны с выводом. Вычислительные функции следует стремиться делать [чистыми](https://ru.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D1%82%D0%BE%D1%82%D0%B0_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8). Вывод — как раз сайд-эффект в данном случае. Следствие из этого следующее. Сейчас Вы внутри функции определяете, что корней нет, но у вызывающего кода нет об этом никакой информации. В тестах видно, что возможно две неразличимые ситуации: когда у уравнения один корень, и когда все коэффициенты нули.
1. Замечание по структуре кода. В данном случае возможно упорядочить таким образом, чтобы блоки были более мелкие. А именно:
  * В первую очередь проверяем, что дискриминант меньше нуля. Это самый короткий блок, ставим его раньше. В этом случае выполняется возврат из функции. В следующем условии нет необходимости в ключевом слове `else`.
  * Далее проверим, что дискриминант равен нулю. Возврат.
  * После этого уже нет смысла писать ни `else`, ни еще один `if`. Остался единственный кейс, дополнительных условий не нужно. Это же позволит избавиться от заглушки в виде `return` в конце.
1. Файл `func.h` переименовали, а include guards в нем забыли.
1. Неконсистентное именование переменных: объект структуры `Coef` назван в верхнем регистре. Ну и в данном случае можно давать название, состоящее не из одной буквы.
1. Для отступов в одних файлах используются пробелы, в других — смесь табов и пробелов.

**Comment by evgeny-p** [comment]
Лабы 4 и 5 приняты.
